annotations:
  artifacthub.io/repository: volumes-psp
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Volumes PSP
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/volumes-psp
  kubewarden/resources: Pod
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - pods
      operations:
      - CREATE
  kubewarden/tag: v0.1.11
appVersion: 0.1.11
description: Pod Security Policy that controls usage of volumes
home: https://github.com/kubewarden/volumes-psp-policy
keywords:
- psp
- pod
- volumes
name: volumes-psp
sources:
- ghcr.io/kubewarden/policies/volumes-psp:v0.1.11
version: 0.1.11
