annotations:
  kubewarden/contextAwareResources: |
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
  kubewarden/displayName: Unique Ingress host
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/unique-ingress-policy
  kubewarden/resources: Ingress
  kubewarden/rules: |
    - apiGroups:
      - networking.k8s.io
      apiVersions:
      - v1
      resources:
      - ingresses
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v0.1.5
appVersion: 0.1.5
description: Requires all Ingress rule hosts to be unique
home: https://github.com/kubewarden/unique-ingress-policy
keywords:
- ingress
- kubewarden
name: ingress-unique-host
sources:
- ghcr.io/kubewarden/policies/unique-ingress-policy:v0.1.5
version: 0.1.5
